import { StyleSheet } from 'react-native';

export const createDiscountStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    paddingHorizontal: 24,
    paddingTop: 32,
    paddingBottom: 24,
  },
  title: {
    fontSize: 34,
    fontWeight: '800',
    letterSpacing: -1,
    marginBottom: 6,
  },
  subtitle: {
    fontSize: 16,
    opacity: 0.6,
    letterSpacing: -0.2,
    fontWeight: '500',
  },
  card: {
    marginHorizontal: 20,
    borderRadius: 20,
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 20,
    elevation: 5,
    marginBottom: 20,
  },
  section: {
    marginBottom: 28,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: '700',
    marginBottom: 12,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    opacity: 0.5,
  },
  field: {
    gap: 8,
    marginBottom: 24,
  },
  fieldCompact: {
    gap: 6,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    letterSpacing: -0.2,
    marginBottom: 2,
  },
  input: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1.5,
    paddingHorizontal: 16,
    fontSize: 16,
    fontWeight: '500',
  },
  suffix: {
    position: 'absolute',
    right: 16,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
  },
  suffixText: {
    fontSize: 16,
    fontWeight: '700',
    opacity: 0.4,
  },
  helper: {
    fontSize: 12,
    marginTop: 6,
    opacity: 0.6,
    fontWeight: '500',
  },
  segmentedControl: {
    flexDirection: 'row',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 0,
    padding: 4,
    gap: 6,
  },
  segmentButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    gap: 8,
    borderRadius: 10,
    borderWidth: 0,
  },
  segmentButtonLeft: {
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
  },
  segmentButtonRight: {
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
  },
  segmentIcon: {
    fontSize: 18,
    fontWeight: '700',
  },
  segmentLabel: {
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  chipRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
  },
  chip: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1.5,
  },
  chipText: {
    fontSize: 15,
    fontWeight: '700',
    letterSpacing: -0.3,
  },
  toggleSection: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: 18,
    borderRadius: 14,
    marginVertical: 8,
  },
  toggleLabel: {
    fontSize: 16,
    fontWeight: '600',
    letterSpacing: -0.3,
    flex: 1,
  },
  toggleHelper: {
    fontSize: 13,
    marginTop: 2,
    opacity: 0.6,
  },
  timeCard: {
    padding: 20,
    borderRadius: 16,
    gap: 18,
    marginTop: 16,
  },
  timeRow: {
    flexDirection: 'row',
    gap: 12,
  },
  daysRow: {
    flexDirection: 'row',
    gap: 10,
    flexWrap: 'wrap',
    marginTop: 4,
  },
  dayChip: {
    width: 44,
    height: 44,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1.5,
  },
  dayChipText: {
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  submitButton: {
    marginHorizontal: 20,
    marginTop: 12,
    marginBottom: 32,
    height: 56,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 6,
  },
  submitText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: -0.4,
  },
  inputWrapper: {
    position: 'relative',
  },
  valueContainer: {
    marginTop: 12,
  },
});